### ISSUE TITLE
Can this be used for runtime types?

### ISSUE THREAD

**Issue by jrunestone** [AVasK/typo#2]
E.g. `typo::type(myvar)` or by parsing the string from `typeid(myvar).name()`? 
Thank you.

**Comment by AVasK** [comment]
Hi Johan, 
Unfortunately the typo doesn't support this use case at the moment since its main goal is constexpr type name retrieval at compile time, which is a bit different of a scope to the dynamic type information. 
What you want can be done using `abi::__cxa_demangle` and I will probably add this to the typo as a separate feature, e.g. `typo::dtype` though it will be less optimised and definitely not constexpr, I agree that it might be useful.
Thanks.

**Comment by jrunestone** [comment]
OK thanks! :+1:
